Nginx-Stats
SteveLTN/https-portal pull request #322
Opened 2022-09-18 21:31 UTC by prilka

This makes ist possible for monitoring systems to get the nginx stats.

2022-09-30 14:18 UTC, s-nagaev requested changes

2022-09-30 14:18 UTC, s-nagaev commented on fs_overlay/var/lib/nginx-conf/nginx.conf.erb
> +    <% unless ENV['NGINX_STATS'] == 'off' %>
I'm deadly sure that it should not be enabled by default. Especially if you are turning access logging off.

2022-09-30 14:21 UTC, SteveLTN commented
Sorry! Crazy busy recently. I'll have a look tomorrow.

2022-10-01 03:22 UTC, SteveLTN commented
I'm going to reject this PR. As @s-nagaev mentioned, I don't think it's a good idea to the stats on by default. You can always add custom block anyways.

2022-10-01 03:22 UTC, closed without merging